### ISSUE TITLE
Duplicate messages when spells wear off

### ISSUE THREAD

**Issue by zach2good** [Spike2D/SimpleLog#6] opened 2022-06-26 19:10 UTC
![image](https://user-images.githubusercontent.com/1389729/175830164-80ec59bf-ba92-473e-8079-57a958c66b88.png)

Only noticed a few times in combat, and now when I'm walking around Windurst - freshly upgraded to 0.9.0a

**Comment by Spike2D** [comment] 2022-06-26 21:04
@zach2good I assume you were by yourself? No party members around or anything right?

This one might be a bit trickier to nail down, will try to replicate.

**Comment by zach2good** [comment] 2022-06-26 21:05
Yeah I've only seen this one while fighting stuff with trusts

**Comment by Spike2D** [comment] 2022-06-26 22:17
I believe I know what's causing this, when different effects wear off at the same time it's interpreting it as a multi-target and trying to condense them, it might been a busy present on the original Battlemod, I'll see what I can do to fix it.

The reason it only happens with trusts is cause they are able to apply buffs rapidly, contrary to players.

Will do some tests and if I'm right fix it.

**Comment by Spike2D** [comment] 2022-06-27 12:43
@zach2good I'm going to need more info to accurately replicate the issue.

Would you be able to track down which buffs wearing out are causing this please?

**Comment by zach2good** [comment] 2022-06-27 12:46
Can do 👍

**Comment by zach2good** [comment] 2022-07-01 06:53
Not very easy to repro, just caught this by chance:
![image](https://user-images.githubusercontent.com/1389729/176840467-371a6fcd-f7c4-48a3-b0f5-eceaa5c1cedb.png)

Play an Ambuscade V2 with Trusts, Yoran-Oran healing and providing Protect+Shell, while talking to the rewards NPC afterwards, got the message

**Comment by Spike2D** [comment] 2022-07-02 02:05
I haven't been able to successfully replicate this, however I'll modify the code to avoid duplicated packets, and see if that solves it, might need some testing on your side Zach, it will be pushed with some more changes to how SimpleLog works with 0x029 packets.

**Comment by Spike2D** [comment] 2022-07-02 11:46
Please see if you can reproduce in 0.10.1b, just released.

**Comment by pogramos** [comment] 2022-07-17 03:35
Well, I've tested with the 0.10.1b and it is kinda intermitent but it is still happening. As you can see, sometimes it duplicates a `single`(in red) message and some times it duplicates a `batch`(in orange) of messages. 

![image](https://user-images.githubusercontent.com/15428949/179382620-bb9c5938-ce59-42fd-b85f-1fc0b1947fbf.png)

**Comment by GetAwayCoxn** [comment] 2022-07-17 19:47
For what its worth I want to say that this happens to me as well, and kind of a lot, and to add something here it happens to me with or without that setting in the GUI that seems to describe trying to prevent this. Unsure if programos has that on or not but doesn't seem to matter for me this happens either way

**Comment by Spike2D** [comment] 2022-07-17 21:11
@GetAwayCoxn Could you share a screenshot of it as well please?

**Comment by GetAwayCoxn** [comment] 2022-07-17 22:37
Sure thing I can get some tonight I'm sure but they will look pretty much exactly like what programos shared here. In fact if you look at his SS there are more examples in that SS then they highlighted. Look at the Blade: Retsu, and the Blade: Jin, and the ranged attack that missed him. I see tons of battle related duplicates like this all the time, doesnt seem to happen with non battle related messages that I've noticed so far though. I see what data I can gather tonight.

**Comment by GetAwayCoxn** [comment] 2022-07-18 03:10
Ok sorry for spamming you guys with github notifications, but a couple of SS's for you, see my prior comment though
![Igotudis_2022 07 17_204155](https://user-images.githubusercontent.com/66495755/179439758-b6aad9cb-5195-4cdc-9134-3f65d0dbedf8.png)
![Igotudis_2022 07 17_204240](https://user-images.githubusercontent.com/66495755/179439761-8c953df0-4597-493f-b4e7-de1238a80b6b.png)
![Igotudis_2022 07 17_204557](https://user-images.githubusercontent.com/66495755/179439768-1e2a351a-993c-4447-8556-26fac685fc77.png)

I cut off the players names as i don't have their permission to post but my char name is w/e. As you can scroll and see, a lot of just duplicate non sense, all battle related. I am only posting to try and contribute to the evidence to find a solution, cheers ~

**Comment by Spike2D** [comment] 2022-07-18 09:07
Don't worry about the spam, funny enough, I think this is a separate issue all together, did it just began with the new release or was it happening prior to it?

Thanks for the report

**Comment by GetAwayCoxn** [comment] 2022-07-19 14:26
Been happening for as long as I can remember but never felt I had enough information to create an issue on it. Kind of got used to it and then I saw this issue opened by programos and thought, well maybe it could be related so figured I'd mention it now.

**Comment by GetAwayCoxn** [comment] 2022-07-29 13:48
Thorny was answering someone else's issue on Discord the other day. A user was having this same/similar problem on ashita v3 battlemod using Farmboy's shim. Thorny mentioned duplicate packets is causing this? I am mentioning only to try and provide more context into whats going on here. Link to the short discord convo:

https://discord.com/channels/264673946257850368/664782430355324939/1000353974140030998

**Comment by Spike2D** [comment] 2022-07-29 14:44
Yeah that's correct, the culprit is duplicated packets, the reason we don't see this issue on windower is because windower handle duplication itself.
I didn't had the time to work on this sadly (summer time) but as soon as I can I'll implement a duplication prevention bit to the code and that should fix the issue.

**Comment by Spike2D** [comment] 2022-09-11 09:45
Fixed with 1.0 release.

Fix by pogramos.

I'll close this for the time being.

**Closed by Spike2D** 2022-09-11 09:45 UTC
Labels: bug
